// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChyPKUhNHD8o_YbDvuWDncseUOsc2uTII',
    appId: '1:304973886723:web:ecd5007733ecb30005e536',
    messagingSenderId: '304973886723',
    projectId: 'align-me',
    authDomain: 'align-me.firebaseapp.com',
    storageBucket: 'align-me.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeo0Orl14p21skBlQbb9vY9T2sYJIp4U',
    appId: '1:304973886723:android:308d47bd34dcc61f05e536',
    messagingSenderId: '304973886723',
    projectId: 'align-me',
    storageBucket: 'align-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGeElRzFIZTKEIqklpwkVaLdZsBqqEHc4',
    appId: '1:304973886723:ios:ddaa47425fe3297f05e536',
    messagingSenderId: '304973886723',
    projectId: 'align-me',
    storageBucket: 'align-me.firebasestorage.app',
    iosBundleId: 'com.example.alignMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGeElRzFIZTKEIqklpwkVaLdZsBqqEHc4',
    appId: '1:304973886723:ios:ddaa47425fe3297f05e536',
    messagingSenderId: '304973886723',
    projectId: 'align-me',
    storageBucket: 'align-me.firebasestorage.app',
    iosBundleId: 'com.example.alignMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChyPKUhNHD8o_YbDvuWDncseUOsc2uTII',
    appId: '1:304973886723:web:183093946b72d29a05e536',
    messagingSenderId: '304973886723',
    projectId: 'align-me',
    authDomain: 'align-me.firebaseapp.com',
    storageBucket: 'align-me.firebasestorage.app',
  );
}
