// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23PSUf1A8YOvlhNf6wyyljmF5gzWRJ-0',
    appId: '1:239200275659:web:81ed2e37855881e7849f4e',
    messagingSenderId: '239200275659',
    projectId: 'alignme-3f209',
    authDomain: 'alignme-3f209.firebaseapp.com',
    storageBucket: 'alignme-3f209.firebasestorage.app',
    measurementId: 'G-RN4YL9RYT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVBjfKm3PJwKxSPYLb_g8cDa2_S-eu6Bk',
    appId: '1:239200275659:android:9ce35bcb48bf2160849f4e',
    messagingSenderId: '239200275659',
    projectId: 'alignme-3f209',
    storageBucket: 'alignme-3f209.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDcA7JMzWTvXseJViFfOelttE6ukeZEoU',
    appId: '1:239200275659:ios:0a4e70be02241e10849f4e',
    messagingSenderId: '239200275659',
    projectId: 'alignme-3f209',
    storageBucket: 'alignme-3f209.firebasestorage.app',
    iosBundleId: 'com.example.alignMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDcA7JMzWTvXseJViFfOelttE6ukeZEoU',
    appId: '1:239200275659:ios:0a4e70be02241e10849f4e',
    messagingSenderId: '239200275659',
    projectId: 'alignme-3f209',
    storageBucket: 'alignme-3f209.firebasestorage.app',
    iosBundleId: 'com.example.alignMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB23PSUf1A8YOvlhNf6wyyljmF5gzWRJ-0',
    appId: '1:239200275659:web:eb94106e5cfbb585849f4e',
    messagingSenderId: '239200275659',
    projectId: 'alignme-3f209',
    authDomain: 'alignme-3f209.firebaseapp.com',
    storageBucket: 'alignme-3f209.firebasestorage.app',
    measurementId: 'G-YQC731XHMY',
  );
}
